development: &default
  adapter: postgresql
  database: tradelink_app_development
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


test:
  <<: *default
  database: tradelink_app_test

production:
  <<: *default
  database: tradelink_app_production
  username: notifier
  password: <%= ENV['TRADELINK_APP_DATABASE_PASSWORD'] %>


